Repository 2024-Winter-Bootcamp-Team-J/backend, pull requests merged in 2025-01, with the labels that each got.

#4 [chroe] 깃 이그노어 설정
  .gitignore
Labels: chore

#20 chore :: S3 초기 세팅
  config/settings.py
  requirements.txt
Labels: chore

#33 Chore/#32 opensearc 개발환경 세팅
  docker-compose.yml
  requirements.txt
Labels: chore

#37 feat : : 검색기능 구현
  config/settings.py
  config/urls.py
  memo/migrations/0001_initial.py
  memo/models.py
  memo/serializers.py
  memo/urls.py
  memo/views.py
  search/__init__.py
  search/admin.py
  search/apps.py
  search/documents.py
  search/migrations/__init__.py
  search/models.py
  search/signals.py
  search/urls.py
  search/views.py
  users/migrations/0001_initial.py
Labels: feat

#42 refactor : : 프롬프팅 최적화
  name_extract_API.py
Labels: refactor

#43 Refactor : : access token을 이용해 swagger의 authorization 접근
  config/settings.py
  config/urls.py
  requirements.txt
Labels: refactor

#47 Refactor : : 검색-노드 연결
  docker-compose.yml
  search/documents.py
  search/signals.py
  search/views.py
Labels: refactor

#50 endpoint정리 완료
  config/urls.py
  memo/urls.py
  node/urls.py
  relation/urls.py
  users/urls.py
Labels: refactor

#52 Chore/#51celery rabbit mq
  config/__init__.py
  config/settings.py
  controller/__init__.py
  controller/admin.py
  controller/apps.py
  controller/migrations/__init__.py
  controller/models.py
  controller/tests.py
  controller/views.py
  docker-compose.yml
  requirements.txt
Labels: chore

#53 Feat/#48 celery rabbit mq
  controller/tasks.py
  controller/views.py
  example.py
  myCelery.py
  node/urls.py
  relation/urls.py
Labels: feat

#56 refactor/#55 프롬프트 개선 2
  name_extract_API.py
Labels: refactor

#65 relation 급하게 수정
  relation/views.py
Labels: feat

#69 Refactor : : controller 노드 관련 에러 수정
  controller/views.py
  node/serializers.py
Labels: refactor

#72 fix : : example_view 제거
  controller/views.py
Labels: fix

#75 [Feat]node_id로 memo list 조회
  memo/serializers.py
  memo/urls.py
  memo/views.py
Labels: refactor

#79 refactor : : relation_type_id추가
  relation/migrations/0001_initial.py
  relation/models.py
  relation/serializers.py
  relation/views.py
Labels: refactor

#81 controller/views.py 중복 삭제
  controller/views.py
Labels: refactor

#76 로깅 개선 1
  config/settings.py
Labels: refactor

#82 refactor : : endPoint 수정
  memo/urls.py
  node/urls.py
  relation/urls.py
  search/urls.py
  search/views.py
Labels: refactor

#84 fix : : celery-beat 비활성화
  config/settings.py
Labels: fix

#89 refactor : : controller앱 수정
  config/settings.py
  controller/views.py
  node/serializers.py
Labels: refactor

#90 fix : : 로그제거
  node/serializers.py
Labels: fix

#92 Fix : : controller에러 수정
  controller/views.py
  node/serializers.py
Labels: fix

#95 fix : : 로그인 에러 수정
  relation/migrations/0001_initial.py
  relation/migrations/0002_initial.py
  relation/migrations/0003_alter_relationtype_user_id.py
Labels: fix

#100 refactor : : 검색기능 수정
  config/settings.py
  search/documents.py
  search/views.py
Labels: refactor

#107 Feat/#96 ai category
  config/__init__.py
  config/myCelery.py
  config/settings.py
  controller/category.jsonl
  controller/category_extract_API.py
  controller/category_fine_tuning.py
  controller/category_json_control.py
  controller/name_extract_API.py
  controller/tasks.py
  controller/views.py
  docker-compose.yml
  relation/apps.py
  relation/migrations/0001_initial.py
Labels: feat, refactor

#108 refactor : : 카테고리 추천 개선1
  controller/category_extract_API.py
  controller/views.py
Labels: refactor
